### ISSUE TITLE
[nri-bundle] support global pod annotations

### ISSUE THREAD

**Issue by nwsparks** [newrelic/helm-charts#876] opened 2022-07-13 19:30 UTC
**Describe the solution you'd like**

Various tools will look for annotations to control behavior, in our case we want to disable logging via fluentbit which is controlled by setting pod annotations. see: https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-annotations

**Describe alternatives you've considered**

we can set it per chart but a global would be nice

**Comment by kang-makes** [comment] 2022-07-14 13:55
Hi @nwsparks,

This is a duplicate of various issues and we have to close it again because we will not be able to find time to solve it.

But I can point you to where we closed the last one: https://github.com/newrelic/helm-charts/pull/794#issuecomment-1118795491

We encourage community contributions and are happy to collaborate on design proposals and pull requests. Feel free to open a PR to the `common-library` to add this feature globally if you would.

If you have any further questions or comments about this, please let us know by replying to this issue.

**Closed as completed by kang-makes** 2022-07-14 13:55 UTC
