### ISSUE TITLE
[newrelic-infrastructure] Bug when trying to configure kubernetes scraping interval

### ISSUE THREAD

**Issue by fr-ser** [newrelic/helm-charts#344] opened 2021-04-27 08:30 UTC
**Bug description**

I was trying to use the `integrations_config` config value to specify a higher scraping interval, than the default 15 seconds.
This was not possible. In addition, I started encountering the behavior of all metrics being reported twice

**Which chart?**
- chart name: newrelic-infrastructure
- chart: 2.4.1
- app: 2.4.0

**What happened?**

This was the value applied:

```yaml
integrations_config:
    - name: nri-kubernetes-config.yml
      data:
        integration_name: com.newrelic.kubernetes
        instances:
            - name: nri-kubernetes
              command: metrics
              interval: 60
```

As a result, I was receiving all metrics **still every 15 seconds** but now I was **receiving them all twice**
This was found by using this NRQL query:
```txt
select * from K8sContainerSample where clusterName = 'data-intelligence-staging' and entityGuid ='MjI1ODEwNXxJTkZSQXxOQXw0MDEwMjcyNjc5NDU0MTUzMTQ2' since 5 minutes ago
```
There I could see that for a single entity I had two values now every 15 seconds.

**What you expected to happen?**

I receive the values once but only every 60 seconds.

**Comment by fr-ser** [comment] 2021-04-27 08:58
My current workaround is to copy/fork the helm chart and mount a file at `/var/db/newrelic-infra/newrelic-integrations/nri-kubernetes-definition.yml`

**Comment by gsanchezgavier** [comment] 2021-04-27 09:25
Hi @fr-ser, thanks for the comments and details on the issue, as you mention is not posible to change the interval from the `nri-kubernetes-config.yml`, the interval has to be changed on the `nri-kubernetes-definition.yml`. 
We have an open [feature request](https://github.com/newrelic/nri-kubernetes/issues/83) that will enable us to implement an easier way to configure the interval with the chart.

**Comment by fr-ser** [comment] 2021-04-27 15:54
But what about me receiving all metrics twice? If the integration config is not for the interval, what else can I do with it?

**Comment by gsanchezgavier** [comment] 2021-04-27 16:12
The integration is currently using this the [standard config](https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-standard-configuration-format/) which supports the interval configuration inside the definition file. The [new configuration](https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-newer-configuration-format/) format which we need to upgrade to unifies these to files in just one yml which supports the interval.
Also these config files are already embedded in the image so when you added the new config using `integrations_config:` this create an extra config which the Infra Agent runs and you end up having the integration running twice.

**Comment by paologallinaharbur** [comment] 2021-06-25 14:45
Closing for now since the bug was caused by an unsupported configuration.

We will carry on the different issue to follow its implementation

**Closed by paologallinaharbur** 2021-06-25 14:45 UTC
Labels: kind/feature
