### ISSUE TITLE
nri-bundle 3.2.11 does not upgrade existing bundle installation.

### ISSUE THREAD

**Issue by TheNakedZealot** [newrelic/helm-charts#626] opened 2021-12-20 18:45 UTC
**Bug description**

The nri-bundle chart pulls in pixie-operator 0.0.15 instead of 0.0.16.

**Version of Helm and Kubernetes**

Helm v2 and Kubernetes 1.19.11

**Which chart?**

nri-bundle 3.2.11

**What happened?**

Bumped version of helm-release and it fails dry-run with the error...

`synchronization of release 'nri-bundle' in namespace 'newrelic' failed: dry-run upgrade failed: dry-run upgrade for comparison failed: error validating "": error validating data: ValidationError(Vizier.spec): unknown field "dataAccess" in dev.px.v1alpha1.Vizier.spec`

**What you expected to happen?**

Upgrade of helm-release to rollout.

**How to reproduce it?**

Note: This chart is deployed via `kind: HelmRelease` in our environment using Flux v1 which leverages the helm-commands seen via Helm v2.

1: Attempt to upgrade helm chart nri-bundle with Pixie enabled with `helm upgrade --dry-run`

**Anything else we need to know?**

Compared CRD in existing in cluster with latest CRD from github with `dataAccess` in spec and they do not match. It looks like the nri-bundle chart pulls in pixie-operator 0.0.15 instead of 0.0.16.

**Comment by mightyshazam** [comment] 2021-12-20 19:40
We tried updating the pixie CRD manually, but it ultimately ends up overwritten during the installation process, so we end up with the invalid field issue.

**Comment by roobre** [comment] 2022-01-14 14:13
Hey, thanks for letting us know and apologies for the delay!
We'll take a look into this ASAP.

**Comment by TheNakedZealot** [comment] 2022-01-21 18:02
Any updates here?

**Comment by kang-makes** [comment] 2022-01-24 08:58
The is a PR waiting to be merged #668 :)

**Comment by davidgit** [comment] 2022-01-28 14:32
Hi @TheNakedZealot!

Con you try to reproduce it with the latest version of the chart?

Thanks!

**Comment by TheNakedZealot** [comment] 2022-02-01 15:28
Yes I am able reproduce the error; it's referencing a `dataAccess` field that does not exist in the chart.

**Comment by roobre** [comment] 2022-02-08 17:47
Hi @TheNakedZealot,

We're still not able to reproduce this on our side. From our knowledge, the Pixie operator should be taking care of updating this CRD. Are you able to reproduce this issue if you run `helm upgrade` without `--dry-run`?

**Comment by roobre** [comment] 2022-03-30 10:07
Closing as stale as this has been pending info for quite some time already.

**Closed by roobre** 2022-03-30 10:07 UTC
Labels: kind/bug, dependencies, triage/needs-information
