### ISSUE TITLE
[nri-kube-events] nri-kube-events chart should support custom attributes

### ISSUE THREAD

**Issue by sjammy6** [newrelic/helm-charts#110] opened 2020-08-26 00:46 UTC
nri-kube-events helm chart should support custom_sttributes just like the rest of the product family (nri-infrastructure). This feature is needed for us to monitor and set up alerts based on the custom_attributes

Reference  code for implementation:
https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-infrastructure/values.yaml#L91
https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-infrastructure/templates/configmap.yaml#L10
https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-infrastructure/templates/daemonset.yaml#L142

**Comment by bpschmitt** [comment] 2021-11-16 00:02
@sjammy6 I've opened a PR with the updates you requested.

https://github.com/newrelic/helm-charts/pull/588

**Comment by davidgit** [comment] 2021-12-23 10:51
Duplicate of #598

**Closed by davidgit** 2021-12-23 10:51 UTC
Labels: triage/accepted
